# FROM maven
# WORKDIR  /opt/server
# COPY pom.xml .
# COPY src  /opt/server/src
# RUN mvn clean package
# RUN mv /opt/server/target/shipping-1.0.jar  /opt/server/shipping.jar 
# ENV CART_ENDPOINT="cart:8080" \
#     DB_HOST="mysql"

# CMD ["java","-jar","shipping.jar"]

########################################################################################################

# stage-1

FROM maven AS Builder
WORKDIR  /opt/server
COPY pom.xml .
COPY src  /opt/server/src
RUN mvn clean package 

# stage -2 downloading from satge-1 and configuring for running app 

FROM eclipse-temurin:17-jre-alpine
EXPOSE 8080
WORKDIR /opt/server 
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop 
ENV CART_ENDPOINT="cart:8080" \
    DB_HOST="mysql" 
COPY --from=builder /opt/server/target/shipping-*.jar /opt/server/shipping.jar 
USER roboshop
CMD ["java","-Djava.net.preferIPv4Stack=true","-Dserver.address=0.0.0.0","-jar","shipping.jar"]
