# FROM node:20
# WORKDIR /opt/server
# COPY package.json .
# COPY *.js .
# RUN npm install 

# ENV MONGO="true" \
#     REDIS_URL="redis://redis:6379" \
#     MONGO_URL="mongodb://mongodb:27017/users"

# CMD [ "node","server.js"]
#################################################################################

 FROM node:20-alpine3.21 AS builder 
 WORKDIR /opt/server
 COPY package.json .
 COPY *.js .
 RUN npm install 

# stage -2 downloading  from stage-1 and configuring the app 
FROM node:20-alpine3.21
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop

ENV  MONGO="true" \
     REDIS_URL="redis://redis:6379" \
     MONGO_URL="mongodb://mongodb:27017/users"
WORKDIR /opt/server
USER roboshop
COPY --from=builder /opt/server /opt/server/
CMD ["node","server.js"]